/**
 * managers/dmManager.js
 * ---------------------------------------------------------------------------
 * The Premium Welcome DM experience — minimal, elegant, dark-mode friendly.
 *
 * Redesigned onboarding modelled on large Discord communities:
 *
 *   Embed 1: Banner — full-width cyber/forge-themed welcome banner shown
 *            at the very top of the DM (image-only embed, the technique
 *            large communities use to place a banner above the content).
 *   Embed 2: Premium welcome — Forge Guardian logo thumbnail, warm forge
 *            accent colour, generous spacing, one randomly-rotated
 *            inspirational quote (10 variants, same layout — see
 *            dmContent.js), timestamp + branded footer.
 *   Embed 3: The server rules (unchanged — reuses the existing rules util
 *            for full backward compatibility).
 *
 * A single Link-button row (Rules / Introduce Yourself / Choose Roles /
 * Community / Support) is attached. Link buttons need zero interaction
 * state and never expire, so they are ideal inside DMs.
 *
 * Every step is best-effort: closed DMs never break the join flow — the
 * function resolves with a status string and never throws.
 * ---------------------------------------------------------------------------
 */

import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder } from 'discord.js';
import { config } from '../config.js';
import { logger } from '../utils/logger.js';
import { getSettings } from '../database/settingsStore.js';
import { rulesDMEmbed } from '../utils/embeds.js';
import { BRAND, buildWelcomeBody } from './dmContent.js';

/**
 * Button row for the welcome DM. All buttons are Link buttons so they work
 * inside DMs (interaction components with customIds also work, but links
 * need zero state and never expire).
 *
 * Discord caps a row at 5 buttons — exactly the 5 we want:
 * Rules / Introduce Yourself / Choose Roles / Community / Support.
 *
 * @param {import('discord.js').Guild} guild
 * @param {object} welcomeSettings
 * @returns {ActionRowBuilder|null} null when no channel is configured.
 */
function buildDMButtons(guild, welcomeSettings) {
  const row = new ActionRowBuilder();
  const channelLink = (channelId) => `https://discord.com/channels/${guild.id}/${channelId}`;

  if (config.channels.rules || config.channels.welcome) {
    row.addComponents(
      new ButtonBuilder()
        .setLabel('Rules')
        .setEmoji('📖')
        .setStyle(ButtonStyle.Link)
        .setURL(channelLink(config.channels.rules || config.channels.welcome))
    );
  }
  if (config.channels.devIntro) {
    row.addComponents(
      new ButtonBuilder()
        .setLabel('Introduce Yourself')
        .setEmoji('👋')
        .setStyle(ButtonStyle.Link)
        .setURL(channelLink(config.channels.devIntro))
    );
  }
  if (config.channels.rolesPicker) {
    row.addComponents(
      new ButtonBuilder()
        .setLabel('Choose Roles')
        .setEmoji('🎭')
        .setStyle(ButtonStyle.Link)
        .setURL(channelLink(config.channels.rolesPicker))
    );
  }
  if (config.channels.community || config.channels.welcome) {
    row.addComponents(
      new ButtonBuilder()
        .setLabel('Community')
        .setEmoji('💬')
        .setStyle(ButtonStyle.Link)
        .setURL(channelLink(config.channels.community || config.channels.welcome))
    );
  }
  if (config.channels.support || config.channels.log) {
    row.addComponents(
      new ButtonBuilder()
        .setLabel('Support')
        .setEmoji('🛟')
        .setStyle(ButtonStyle.Link)
        .setURL(channelLink(config.channels.support || config.channels.log))
    );
  }

  return row.components.length > 0 ? row : null;
}

/**
 * Image-only banner embed — placed FIRST so the cyber/forge welcome banner
 * renders at the very top of the DM (Discord draws setImage below embed
 * text, so a dedicated leading embed is the clean way to get a top banner).
 *
 * @returns {EmbedBuilder}
 */
export function welcomeBannerEmbed() {
  return new EmbedBuilder().setColor(BRAND.accent).setImage(BRAND.bannerUrl);
}

/**
 * Build the premium minimal welcome embed.
 *
 * Design decisions (see task spec):
 *   - Warm forge amber accent (BRAND.accent) — elegant in dark & light mode.
 *   - Forge Guardian logo as the thumbnail.
 *   - Timestamp + "Developer's Forge • Learn • Build • Grow" footer.
 *   - Body content generated by dmContent.buildWelcomeBody with dynamic
 *     variables and one of 10 rotating quotes.
 *
 * @param {import('discord.js').GuildMember} member
 * @returns {EmbedBuilder}
 */
export function premiumWelcomeDMEmbed(member) {
  const guild = member.guild;
  const joinedTs = Math.floor((member.joinedTimestamp ?? Date.now()) / 1000);

  const body = buildWelcomeBody({
    username: member.user.username,
    displayName: member.displayName ?? member.user.globalName ?? member.user.username,
    memberCount: guild.memberCount,
    joinDate: `<t:${joinedTs}:D>`,
    serverName: guild.name,
  });

  return new EmbedBuilder()
    .setColor(BRAND.accent)
    .setAuthor({
      name: guild.name,
      iconURL: guild.iconURL({ size: 128 }) ?? undefined,
    })
    .setDescription(body)
    .setThumbnail(BRAND.logoUrl)
    .setFooter({
      text: BRAND.footer,
      iconURL: guild.iconURL({ size: 64 }) ?? undefined,
    })
    .setTimestamp();
}

/**
 * Send the full premium welcome DM to a new member. Never throws.
 *
 * Contract preserved from the previous implementation — callers
 * (events/guildMemberAdd.js) rely on the exact status strings for the
 * Telegram notification, the member store and the security profile.
 *
 * @param {import('discord.js').GuildMember} member
 * @returns {Promise<'Delivered'|'Disabled'|'Failed (DMs closed)'>} status.
 */
export async function sendWelcomeDM(member) {
  const settings = await getSettings(member.guild.id);
  const wc = settings.welcome;
  if (!wc.dmEnabled) return 'Disabled';

  const buttons = buildDMButtons(member.guild, wc);

  try {
    await member.send({
      embeds: [
        welcomeBannerEmbed(),
        premiumWelcomeDMEmbed(member),
        rulesDMEmbed(member.guild.name),
      ],
      ...(buttons ? { components: [buttons] } : {}),
    });
    return 'Delivered';
  } catch (error) {
    // Closed DMs (error 50007) or any other delivery failure must never
    // interrupt the join flow — log and report gracefully.
    logger.warn(`Failed to send welcome DM to ${member.user.tag}: ${error.message}`);
    return 'Failed (DMs closed)';
  }
}
